version: "2.3"
services:
  octopus:
    build: .
    image: new_octopus:v2
    runtime: nvidia
    working_dir: /app
    volumes:
      - $PWD:/app
      - /ai_data:/ai_data
    # command: tail -f /dev/null
    command: python app.py
    expose:
      - 5004
    ports:
      - 5004:5004